NAME=lukedeo/ji
VERSION=1.0

all: build

build:
	docker build -t $(NAME):$(VERSION) .

tag:
	docker tag $(NAME):$(VERSION) $(NAME):latest

push: tag
	docker push $(NAME):$(VERSION)
	docker push $(NAME):latest

